[module]
path = "ecosystem::web"

[dependencies]
"ecosystem::websocket" = "0.1.0"
"ecosystem::compress" = "0.1.0"
"ecosystem::mime" = "0.1.0"
"ecosystem::http" = "0.1.0"
"ecosystem::request" = "0.1.0"
"ecosystem::textproto" = "0.1.0"

[native]
go-module = "example.com/goml-ecosystem/web"
